version: '3.8'

services: 
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
  
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: DockerfileIntegrationTests
    environment: 
      - WAIT_HOSTS=mongodb:27017
      - ConnectionString=${ConnectionString}
      - DbName=${DbName}
    volumes:
      - ${DefaultWorkingDirectory}/testresults:${TestsResultPath}