version: '3.8'

services: 
  mongo:
    container_name: mongo
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=covidbot
      - MONGO_INITDB_ROOT_PASSWORD=nXj3IhmMgR5olSzxqXeB
    volumes:
        - mongo-db:/var/lib/mongo
    ports:
      - 27017:27017
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=covidbot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nXj3IhmMgR5olSzxqXeB
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=covidbot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=nXj3IhmMgR5olSzxqXeB
      - ME_CONFIG_BASICAUTH_USERNAME=kwiatek
      - ME_CONFIG_BASICAUTH_PASSWORD=YMjBgvUeOxfg0HEGJ7M6
    depends_on: 
      - mongo
    ports:
      - 8888:8081

volumes:
  mongo-db: