jobs:
  - job: Build
    displayName: Execute build and push to DockerHub
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: '$(RepositoryName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
        addPipelineData: false