jobs:
  - job: Build
    displayName: Execute build and push to DockerHub
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: '$(RepositoryName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '$(BuildArgs)'

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: '$(RepositoryName)'
        command: 'push'