# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:   
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - LICENSE

pr: none

variables:
  - template: templates/variables.yml

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: templates/build.yml

  - stage: UnitTest
    displayName: Unit tests
    jobs:
      - template: templates/xunit.yml
        parameters:
           ImageName: 'xunittests:$(Build.BuildId)'

  - stage: IntegrationTests
    displayName: Integration tests
    jobs:
      - template: templates/integrationtests.yml
